name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Change to Chapter 11
        run:  cd './Chapter 11/Cards_project/'
      - name: print working dir
        run:  pwd
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run Tox
        run: tox -e py